import Enum from '~/utils/enum.js'

export default new Enum({
  AUTOMATION_MAINTENANCE: 'AUTOMATION_MAINTENANCE',
  AUTOMATION_VEHICLE_SALE: 'AUTOMATION_VEHICLE_SALE',
  AUTOMATION_NEW_VEHICLE_SALE: 'AUTOMATION_NEW_VEHICLE_SALE',
  AUTOMATION_USED_VEHICLE_SALE: 'AUTOMATION_USED_VEHICLE_SALE',
  AUTOMATION_VEHICLE_INSPECTION: 'AUTOMATION_VEHICLE_INSPECTION'
})
