const dataTypes = require('../../../../../common/models/data/type/data-types');

const typeFormatter = {};
typeFormatter[dataTypes.MAINTENANCE] = [
  'INTER',
  'apv',
  'APV',
  'MECANIQUE',
  'intervention carrosserie',
  'intervention mécanique',
  'SAV',
  'Entretien',
  'Atelier',
  'CARROSSERIE',
  'Dépannage',
  'SAV SAINT CLOUD',
  'Intervention inconnu',
  'Intervention atelier',
  'TYPE : Intervention Atelier avec RDV',
  'TYPE : Intervention Atelier sans RDV',
  'Après-Vente',
  'Intervention Atelier',
  'Carrosserie avec assurance',
  'Carrosserie sans assurance',
  'Facture - Atelier',
  'SAV MANTES LA JOLIE',
  'SAV RUEIL',
  'ATELIER',
];
typeFormatter[dataTypes.NEW_VEHICLE_SALE] = [
  'VN',
  'TYPE : Ventes VN et achats VO',
  'Vente véhicule neuf',
  'V.N.',
  'Vente VN',
  'vn',
  'Parc VN',
  'VN CHAMBOURCY',
  'SAV CHAMBOURCY',
  'VN MANTES LA JOLIE',
  'VN Facture principale - VN',
  'VN SAINT CLOUD',
  'VD',
  'VN RUEIL',
  'VN ORGEVAL',
  '1',
  '4',
  '7',
  'N',
  'Vente matériel neuf',
  '10',
  'neuf',
  'direction',
  '16',
];
typeFormatter[dataTypes.USED_VEHICLE_SALE] = [
  'vo',
  'VO',
  'Parc VO',
  'VO Facture principale - VO',
  'VO CHAMBOURCY',
  'VO MANTES LA JOLIE',
  'VO SAINT CLOUD',
  'VO RUEIL',
  'VO ORGEVAL',
  '2',
  '5',
  '8',
  '11',
  '14',
  'occasion',
  'TYPE : Ventes et achats VO',
  "Vente matériel d'occasion",
  'U',
  'V.O.',
  'Vente VO',
  'Vente véhicule occasion',
  'Achat VO',
];

module.exports = typeFormatter;
