module.exports = {
  _reference: 'generic',
  dataRecordCompletedAt: [
    'dataRecordCompletedAt',
    'dateinter',
    'Date de dernière visite',
    'date',
    'Date de facture',
    'Date MEC',
    'Date Facture',
    'Date Achat',
    'Date Facturation',
    'D. Dernier OR',
    'Commande Date livraison réelle',
    'DATE FACT ATE',
    'PrestationDate',
  ],
  billedAt: null,
  vehicleRegistrationFirstRegisteredAt: ['vehicleRegistrationPlate'],
  gender: [
    'gender',
    'genre',
    'juridique',
    'Titre',
    'Civilité',
    'Client Propriétaire (titre)',
    'Client Civilité courte',
    'CIVILITE',
    'Title',
  ],
  fullName: ['nom', 'Nom', 'Nom Client'],
  lastName: ['LastName', 'lastName', 'nom', 'Nom', 'Client Propriétaire (nom 1)', 'Client Nom', 'NOM DU CLIENT'],
  firstName: ['Firstname', 'firstName', 'prénom', 'Prénom', 'Client Propriétaire (prénom)', 'Client Prénom'],
  vehicleRegistrationPlate: ['Immatriculation', 'IMMAT'],
  homePhone: ['homePhone'],
  mobilePhone: [
    'mobilePhone',
    'Tél. Portable',
    'portable',
    'Tel Portable',
    'courriel',
    'Tél. Mobile',
    'Tél Portable',
    'Client Portable',
    'PORTABLE',
    'Téléphone portable',
    'MobileNumber',
  ],
  officePhone: ['officePhone'],
  fax: ['fax'],
  email: [
    'email',
    'e-mail',
    'mail',
    'Courriel',
    'Email',
    'Mail',
    'E-mail Particulier',
    'Adresse électronique',
    'Mail Domicile',
    'Client Email',
    'EMAIL',
    'courriel',
  ],
  streetAddress: ['streetAddress', 'Adresse 1', 'rue', 'Adresse'],
  postCode: ['postCode', 'Code Postal', 'cp', 'C. Postal'],
  countryCode: null,
  city: ['city', 'ville', 'Ville', 'distributeur', 'VILLE', 'City'],
  vehicleMake: ['vehicleMake', 'marque', 'Marque', 'Marque (véhicule)', 'Offre Marque', 'MARQUE', 'Manufacturer'],
  vehicleCategoryId: null,
  vehicleModel: [
    'vehicleModel',
    'modele',
    'Série',
    'Modéle véhicule',
    'Modèle',
    'Version',
    'Offre Modèle',
    'LIBELLE MODELE',
    'Model',
  ],
  vehicleMileage: ['vehicleMileage'],
  vehicleVin: ['vehicleVin', 'VIN', 'vin'],
  rowType: ['RtYpE', 'Service', 'Offre Type offre', 'Prestation'],
  foreigns_providedFrontDeskUserName: [
    'Nom vendeur1',
    'Libellé réceptionnaire',
    'Nom Conseiller comm. principal',
    'vendeur',
    'interlocuteur',
    'Interlocuteur',
    'Nom Conseiller comm． principal',
    'Réceptionnaire',
    'Dernier Réceptionnaire',
    'NUMERO RECEPTIONNAIRE',
    'ContactName'
  ],
  foreigns_providedCustomerId: [],
  foreigns_providedGarageId: null,
  optOutMailing: ['dpo', 'DPO', 'rgpd', 'RGPD', 'gdpr', 'GDPR'],
  optOutSMS: ['sms', 'SMS'],
  id: '1',
};
