/**
 * This file allow you to use any component register here in any .vue file
 */

import Vue from "vue";

import AppText from "~/components/ui/AppText";
import BaseLayout from "~/components/ui/BaseLayout";
import BaseLayoutNoSidebar from "~/components/ui/BaseLayoutNoSidebar";
import Breadcrumbs from "~/components/ui/breadcrumbs/Breadcrumbs";
import BreadcrumbsItem from "~/components/ui/breadcrumbs/BreadcrumbsItem";
import Button from "~/components/ui/Button";
import ButtonGroup from "~/components/ui/ButtonGroup";
import Card from "~/components/ui/Card";
import CardChart from "~/components/ui/CardChart";
import CardDropdown from "~/components/ui/CardDropdown";
import CheckBox from '~/components/ui/CheckBox';
import Dropdown from "~/components/ui/Dropdown";
import DropdownContent from "~/components/ui/DropdownContent";
import ElapsedTime from "~/components/ui/ElapsedTime";
import FieldGroup from "~/components/ui/FieldGroup";
import FormattedValueWithMissingHandling
  from "~/components/ui/FormattedValueWithMissingHandling";
import Gauge from "~/components/ui/Gauge";
import GaugeEreputation from "~/components/ui/GaugeEreputation";
import Header from "~/components/ui/Header";
import HistoryItem from "~/components/ui/history/HistoryItem";
import InlineList from "~/components/ui/InlineList";
import InputBasic from "~/components/ui/InputBasic";
import InputMaterial from "~/components/ui/InputMaterial";
import InterfaceLink from "~/components/ui/InterfaceLink";
import KPI from "~/components/ui/KPI";
import Notification from "~/components/ui/Notification";
import ModalBase from "~/components/ui/ModalBase";
import ModalMessage from "~/components/ui/ModalMessage";
import ModalMobile from "~/components/ui/ModalMobile";
import ModalNoAccess from "~/components/ui/ModalNoAccess";
import MultiSelectMaterial from "~/components/ui/MultiSelectMaterial";
import OldCardChart from "~/components/ui/OldCardChart";
import OldKPI from "~/components/ui/OldKPI";
import PhoneInputMaterial from "~/components/ui/PhoneInputMaterial";
import PlaceholderLoading from "~/components/ui/PlaceholderLoading";
import Radio from "~/components/ui/Radio";
import RatingBadge from "~/components/ui/RatingBadge";
import RatingStar from "~/components/ui/RatingStar";
import SelectBasic from "~/components/ui/SelectBasic";
import SelectMaterial from "~/components/ui/SelectMaterial";
import ServiceWorker from "~/components/ui/ServiceWorker";
import SetupStep from "~/components/ui/SetupStep";
import Sidebar from "~/components/ui/sidebar/Sidebar";
import SidebarItem from "~/components/ui/sidebar/SidebarItem";
import Skeleton from "~/components/ui/Skeleton";
import StarsScore from "~/components/ui/StarsScore.vue";
import Stats from "~/components/ui/Stats";
import StatusDiode from '~/components/ui/StatusDiode';
import Steps from "~/components/ui/steps/Steps";
import StepsItem from "~/components/ui/steps/StepsItem";
import Tab from "~/components/ui/Tab";
import Table from "~/components/ui/table/Table";
import TableHeader from "~/components/ui/table/TableHeader";
import TableRow from "~/components/ui/table/TableRow";
import TableRowCell from "~/components/ui/table/TableRowCell";
import Tag from '~/components/ui/Tag';
import TextareaMaterial from "~/components/ui/TextareaMaterial";
import ThumbScore from "~/components/ui/ThumbScore";
import Tile from "~/components/ui/Tile";
import TileStats from "~/components/ui/TileStats";
import Title from "~/components/ui/Title";
import Toggle from "~/components/ui/Toggle";


Vue.component("AppText", AppText);
Vue.component("BaseLayout", BaseLayout);
Vue.component("BaseLayoutNoSidebar", BaseLayoutNoSidebar);
Vue.component("Breadcrumbs", Breadcrumbs);
Vue.component("BreadcrumbsItem", BreadcrumbsItem);
Vue.component("Button", Button);
Vue.component("ButtonGroup", ButtonGroup);
Vue.component("Card", Card);
Vue.component("CardChart", CardChart);
Vue.component("CardDropdown", CardDropdown);
Vue.component("CheckBox", CheckBox);
Vue.component("Dropdown", Dropdown);
Vue.component("DropdownContent", DropdownContent);
Vue.component("ElapsedTime", ElapsedTime);
Vue.component("FieldGroup", FieldGroup);
Vue.component(
  "FormattedValueWithMissingHandling",
  FormattedValueWithMissingHandling
);
Vue.component("Gauge", Gauge);
Vue.component("GaugeEreputation", GaugeEreputation);
Vue.component("Header", Header);
Vue.component("HistoryItem", HistoryItem);
Vue.component("InlineList", InlineList);
Vue.component("InputBasic", InputBasic);
Vue.component("InputMaterial", InputMaterial);
Vue.component("InterfaceLink", InterfaceLink);
Vue.component("KPI", KPI);
Vue.component("ModalBase", ModalBase);
Vue.component("ModalMessage", ModalMessage);
Vue.component("ModalMobile", ModalMobile);
Vue.component("ModalNoAccess", ModalNoAccess);
Vue.component("MultiSelectMaterial", MultiSelectMaterial);
Vue.component("Notification", Notification);
Vue.component("OldCardChart", OldCardChart);
Vue.component("OldKPI", OldKPI);
Vue.component("PhoneInputMaterial", PhoneInputMaterial);
Vue.component("PlaceholderLoading", PlaceholderLoading);
Vue.component("Radio", Radio);
Vue.component("RatingBadge", RatingBadge);
Vue.component("RatingStar", RatingStar);
Vue.component("SelectBasic", SelectBasic);
Vue.component("SelectMaterial", SelectMaterial);
Vue.component("ServiceWorker", ServiceWorker);
Vue.component("SetupStep", SetupStep);
Vue.component("Sidebar", Sidebar);
Vue.component("SidebarItem", SidebarItem);
Vue.component("StarsScore", StarsScore);
Vue.component("Stats", Stats);
Vue.component("Steps", Steps);
Vue.component("StepsItem", StepsItem);
Vue.component("Skeleton", Skeleton);
Vue.component("StatusDiode", StatusDiode);
Vue.component("Tab", Tab);
Vue.component("Table", Table);
Vue.component("TableHeader", TableHeader);
Vue.component("TableRow", TableRow);
Vue.component("TableRowCell", TableRowCell);
Vue.component("Tag", Tag);
Vue.component("TextareaMaterial", TextareaMaterial);
Vue.component("ThumbScore", ThumbScore);
Vue.component("Tile", Tile);
Vue.component("TileStats", TileStats);
Vue.component("Title", Title);
Vue.component("Toggle", Toggle);
