const { AutoBrands, CaravanBrands, MotoBrands, OtherBrands } = require('../../../../../frontend/utils/enumV2');

module.exports = {
  '106': AutoBrands.PEUGEOT,
  A3: AutoBrands.AUDI,
  ABARTH: AutoBrands.ABARTH,
  ADRIA: CaravanBrands.ADRIA,
  AIXAM: OtherBrands.AIXAM,
  AJS: OtherBrands.AJS,
  'ALFA ROME': AutoBrands.ALFA_ROMEO,
  ALFA: AutoBrands.ALFA_ROMEO,
  'ALFA-ROMEO': AutoBrands.ALFA_ROMEO,
  'ALPHA ROMEO': AutoBrands.ALFA_ROMEO,
  'ALFA ROMEO': AutoBrands.ALFA_ROMEO,
  ARCHIVE: OtherBrands.ARCHIVE,
  'ASTON MARTIN': AutoBrands.ASTON_MARTIN,
  AUDI: AutoBrands.AUDI,
  AUSTIN: OtherBrands.AUSTIN,
  AUTOSTAR: CaravanBrands.AUTOSTAR,
  'AUTRES POLO': AutoBrands.VOLKSWAGEN,
  BAVARIA: CaravanBrands.BAVARIA,
  BELL: OtherBrands.BELLIER,
  BENIMAR: CaravanBrands.BENIMAR,
  BMW: AutoBrands.BMW,
  BULLIT: OtherBrands.BULLIT,
  BURSTNER: CaravanBrands.BURSTNER,
  CADILLAC: AutoBrands.CADILLAC,
  CAMPEREVE: CaravanBrands.CAMPEREVE,
  CAMPSTER: CaravanBrands.CAMPSTER,
  CARADO: CaravanBrands.CARADO,
  CARAVELAIR: CaravanBrands.CARAVELAIR,
  CARTHAGO: CaravanBrands.CARTHAGO,
  'CF MOTO': OtherBrands.CF_MOTO,
  CHALLENGER: CaravanBrands.CHALLENGER,
  CHAT: OtherBrands.CHATENET,
  CHAUSSON: CaravanBrands.CHAUSSON,
  CHEV: AutoBrands.CHEVROLET,
  CHEVROLET: AutoBrands.CHEVROLET,
  CHRY: AutoBrands.CHRYSLER,
  CHRYSLER: AutoBrands.CHRYSLER,
  CI: CaravanBrands.CI,
  CITR: AutoBrands.CITROEN,
  'CITROEN C5': AutoBrands.CITROEN,
  CITROEN: AutoBrands.CITROEN,
  'CLASSE B': AutoBrands.MERCEDES_BENZ,
  CROSSCAMP: CaravanBrands.CROSSCAMP,
  DACI: AutoBrands.DACIA,
  DACIA: AutoBrands.DACIA,
  DAELIM: MotoBrands.DAELIM,
  DAEWOO: OtherBrands.DAEWOO,
  DAIHATSU: AutoBrands.DAIHATSU,
  DAIH: AutoBrands.DAIHATSU,
  DETHLEFFS: CaravanBrands.DETHLEFFS,
  DIGUE: CaravanBrands.DIGUE,
  DODGE: AutoBrands.DODGE,
  ELIOS: CaravanBrands.ELIOS,
  ELNAGH: CaravanBrands.ELNAGH,
  ERIBA: CaravanBrands.ERIBA,
  ETRUSCO: CaravanBrands.ETRUSCO,
  EUROCKA: OtherBrands.EUROCKA,
  FANTIC: OtherBrands.FANTIC,
  FENDT: CaravanBrands.FENDT,
  'FIAT IDEA': AutoBrands.FIAT,
  FIAT: AutoBrands.FIAT,
  FLEURETTE: CaravanBrands.FLEURETTE,
  FONTVENDOME: CaravanBrands.FONTVENDOME,
  'FORD   CEE': AutoBrands.FORD,
  'FORD CHALLENGER': AutoBrands.FORD,
  'FORD CUSTOM': AutoBrands.FORD,
  'FORD KA ESSENCE': AutoBrands.FORD,
  'FORD MINI BUS': AutoBrands.FORD,
  FORD: AutoBrands.FORD,
  'FORD EURO': AutoBrands.FORD,
  FRANKIA: CaravanBrands.FRANKIA,
  GEOS: OtherBrands.GEOS,
  GIOTTILINE: CaravanBrands.GIOTTILINE,
  GLOBECAR: CaravanBrands.GLOBECAR,
  GUNSHOT: OtherBrands.GUNSHOT,
  HARL: MotoBrands.HARLEY_DAVIDSON,
  HOBBY: CaravanBrands.HOBBY,
  HOND: AutoBrands.HONDA,
  HONDA: AutoBrands.HONDA,
  HUMMER: AutoBrands.HUMMER,
  HYMER: CaravanBrands.HYMER,
  HYMERERIBA: CaravanBrands.HYMERERIBA,
  HYUN: AutoBrands.HYUNDAI,
  HYUNDAI: AutoBrands.HYUNDAI,
  INFINITI: AutoBrands.INFINITI,
  ITINEO: CaravanBrands.ITINEO,
  IVEC: AutoBrands.IVECO,
  IVECO: AutoBrands.IVECO,
  JAGU: AutoBrands.JAGUAR,
  JAGUAR: AutoBrands.JAGUAR,
  JEEP: AutoBrands.JEEP,
  KAWA: MotoBrands.KAWASAKI,
  KIA: AutoBrands.KIA,
  KNAUS: CaravanBrands.KNAUS,
  LABOHEME: CaravanBrands.LABOHEME,
  LAIKA: CaravanBrands.LAIKA,
  LANC: AutoBrands.LANCIA,
  LANCIA: AutoBrands.LANCIA,
  'LAND ROVER': AutoBrands.LAND_ROVER,
  LAND: AutoBrands.LAND_ROVER,
  'LAND-ROVER': AutoBrands.LAND_ROVER,
  LEVOYAGEUR: CaravanBrands.LEVOYAGEUR,
  LEXUS: AutoBrands.LEXUS,
  LIGI: OtherBrands.LIGIER,
  LINHAI: OtherBrands.LINHAI,
  MAGPOWER: OtherBrands.MAGPOWER,
  MASAI: OtherBrands.MASAI,
  MAZD: AutoBrands.MAZDA,
  MAZDA: AutoBrands.MAZDA,
  MCC: AutoBrands.SMART,
  MCLOUIS: CaravanBrands.MCLOUIS,
  MERC: AutoBrands.MERCEDES_BENZ,
  MERCEDES: AutoBrands.MERCEDES_BENZ,
  'MERCEDES-BENZ': AutoBrands.MERCEDES_BENZ,
  MG: AutoBrands.MG,
  MINI: AutoBrands.MINI,
  MITS: AutoBrands.MITSUBISHI,
  MITSUBISHI: AutoBrands.MITSUBISHI,
  MOBILVETTA: CaravanBrands.MOBILVETTA,
  MOOVEO: CaravanBrands.MOOVEO,
  MOTOBECANE: MotoBrands.MOTOBECANE,
  MOTRAC: OtherBrands.MOTRAC,
  MSC: AutoBrands.MITSUBISHI,
  NISS: AutoBrands.NISSAN,
  NISSAN: AutoBrands.NISSAN,
  NOTIN: CaravanBrands.NOTIN,
  OPEL: AutoBrands.OPEL,
  ORION: OtherBrands.ORION,
  PEUG: AutoBrands.PEUGEOT,
  PEUGEOT: AutoBrands.PEUGEOT,
  'PGT SS VIN': AutoBrands.PEUGEOT,
  PHOENIX: CaravanBrands.PHOENIX,
  PIAGGIO: MotoBrands.PIAGGIO,
  PILOTE: CaravanBrands.PILOTE,
  PORSCHE: AutoBrands.PORSCHE,
  POSSL: CaravanBrands.POSSL,
  QG: OtherBrands.QG,
  QUA2: OtherBrands.QUATTRO,
  RAPIDO: CaravanBrands.RAPIDO,
  RENA: AutoBrands.RENAULT,
  RENAULT: AutoBrands.RENAULT,
  RIMOR: CaravanBrands.RIMOR,
  ROLLERTEAM: CaravanBrands.ROLLERTEAM,
  SAAB: AutoBrands.SAAB,
  SEA: CaravanBrands.SEA,
  'SEAT IBIZA': AutoBrands.SEAT,
  SEAT: AutoBrands.SEAT,
  'SERIE 1': AutoBrands.BMW,
  SHERCO: OtherBrands.SHERCO,
  SKOD: AutoBrands.SKODA,
  SKODA: AutoBrands.SKODA,
  SKYTEAM: OtherBrands.SKYTEAM,
  SMART: AutoBrands.SMART,
  SOCO: OtherBrands.SOCO,
  SSANGYONG: AutoBrands.SSANGYONG,
  STERCKEMAN: CaravanBrands.STERCKEMAN,
  STYLEVAN: CaravanBrands.STYLEVAN,
  SUNLIGHT: CaravanBrands.SUNLIGHT,
  SUZU: AutoBrands.SUZUKI,
  SUZUKI: AutoBrands.SUZUKI,
  TALBOT: OtherBrands.TALBOT,
  TEC: CaravanBrands.TEC,
  TGB: OtherBrands.TGB,
  TOURAN: AutoBrands.VOLKSWAGEN,
  TOYO: AutoBrands.TOYOTA,
  TOYOTA: AutoBrands.TOYOTA,
  Toyota: AutoBrands.TOYOTA,
  TRIGANO: CaravanBrands.TRIGANO,
  'V.W': AutoBrands.VOLKSWAGEN,
  VERIFAUTOS: OtherBrands.VERIFAUTOS,
  VITO: CaravanBrands.VITO,
  VOLK: AutoBrands.VOLKSWAGEN,
  VOLKSWAGE: AutoBrands.VOLKSWAGEN,
  VOLKSWAGEN: AutoBrands.VOLKSWAGEN,
  VOLV: AutoBrands.VOLKSWAGEN,
  VOLVO: AutoBrands.VOLVO,
  VUL: '',
  VW: AutoBrands.VOLKSWAGEN,
  'V.W.': AutoBrands.VOLKSWAGEN,
  WEINSBERG: CaravanBrands.WEINSBERG,
  YAMA: MotoBrands.YAMAHA,
  YIYING: OtherBrands.YIYING,
  'ZANTIA BREK': AutoBrands.CITROEN,
  ZHENHUA: OtherBrands.ZHENHUA,
  ZONTES: OtherBrands.ZONTES,
};
