/* initial chart configuration */
import ChartConfigValidator from './configValidator';
import { ChartConfigPages, ChartConfigViews, ChartConfigFormats } from '../enumV2';


/** @type {CHART_CONFIGURATION} - Full chart configuration object */
const CHART_CONFIGURATION = {
  shouldRefreshData: true,
  ghPeriods: [],
  config: {
    labels: [],
    labelsColors: [],
  },
  components: {
    //--------------------------------------------------------------------------------------//
    //                                        Leads                                         //
    //--------------------------------------------------------------------------------------//

    [ChartConfigPages.COCKPIT_LEADS_GARAGES]: {
      StatsLeadsUnprocessed: {
        loading: false,
        view: ChartConfigViews.KPI,
        stepSize: 25,
        min: 0,
        max: 100,
        format: ChartConfigFormats.PERCENT_ROUND,
        field: 'countLeadsUntouched',
        generalStatsLabel: 'leadUntreated',
        target: { label: 'leadsUntouched', dataSet: [] },
      },
      StatsLeadsProcessed: {
        loading: false,
        view: ChartConfigViews.KPI,
        stepSize: 25,
        min: 0,
        max: 100,
        format: ChartConfigFormats.PERCENT_ROUND,
        field: 'countLeadsTouched',
        generalStatsLabel: 'leadPendingOrProcessed',
        target: { label: 'leadsTouched', dataSet: [] },
      },
      StatsLeadConverted: {
        loading: false,
        view: ChartConfigViews.KPI,
        stepSize: 25,
        min: 0,
        max: 100,
        format: ChartConfigFormats.PERCENT,
        field: 'countLeadsClosedWithSale',
        generalStatsLabel: 'leadConverted',
        target: { label: 'leadsClosedWithSale', dataSet: [] },
      },
    },
    [ChartConfigPages.COCKPIT_LEADS_TEAM]: {
      StatsLeadsUnprocessed: {
        loading: false,
        view: ChartConfigViews.KPI,
        stepSize: 25,
        min: 0,
        max: 100,
        format: ChartConfigFormats.PERCENT_ROUND,
        field: 'countLeadsUntouched',
        generalStatsLabel: 'leadUntreated',
        target: { label: 'leadsUntouched', dataSet: [] },
      },
      StatsLeadsProcessed: {
        loading: false,
        view: ChartConfigViews.KPI,
        stepSize: 25,
        min: 0,
        max: 100,
        format: ChartConfigFormats.PERCENT_ROUND,
        field: 'countLeadsTouched',
        generalStatsLabel: 'leadPendingOrProcessed',
        target: { label: 'leadsTouched', dataSet: [] },
      },
      StatsLeadConverted: {
        loading: false,
        view: ChartConfigViews.KPI,
        stepSize: 25,
        min: 0,
        max: 100,
        format: ChartConfigFormats.PERCENT,
        field: 'countLeadsClosedWithSale',
        generalStatsLabel: 'leadConverted',
        target: { label: 'leadsClosedWithSale', dataSet: [] },
      },
    },
    [ChartConfigPages.COCKPIT_LEADS_SOURCES]: {
      StatsLeadsUnprocessed: {
        loading: false,
        view: ChartConfigViews.KPI,
        stepSize: 25,
        min: 0,
        max: 100,
        format: ChartConfigFormats.PERCENT_ROUND,
        field: 'countLeadsUntouched',
        generalStatsLabel: 'leadUntreated',
        target: { label: 'leadsUntouched', dataSet: [] },
      },
      StatsLeadsProcessed: {
        loading: false,
        view: ChartConfigViews.KPI,
        stepSize: 25,
        min: 0,
        max: 100,
        format: ChartConfigFormats.PERCENT_ROUND,
        field: 'countLeadsTouched',
        generalStatsLabel: 'leadPendingOrProcessed',
        target: { label: 'leadsTouched', dataSet: [] },
      },
      StatsLeadConverted: {
        loading: false,
        view: ChartConfigViews.KPI,
        stepSize: 25,
        min: 0,
        max: 100,
        format: ChartConfigFormats.PERCENT,
        field: 'countLeadsClosedWithSale',
        generalStatsLabel: 'leadConverted',
        target: { label: 'leadsClosedWithSale', dataSet: [] },
      },
    },
    [ChartConfigPages.COCKPIT_LEADS_FOLLOWED]: {
      StatsLeadsUnprocessed: {
        loading: false,
        view: ChartConfigViews.KPI,
        stepSize: 25,
        min: 0,
        max: 100,
        format: ChartConfigFormats.PERCENT_ROUND,
        field: 'countLeadsUntouched',
        generalStatsLabel: 'leadUntreated',
        target: { label: 'leadsUntouched', dataSet: [] },
      },
      StatsLeadsProcessed: {
        loading: false,
        view: ChartConfigViews.KPI,
        stepSize: 25,
        min: 0,
        max: 100,
        format: ChartConfigFormats.PERCENT_ROUND,
        field: 'countLeadsTouched',
        generalStatsLabel: 'leadPendingOrProcessed',
        target: { label: 'leadsTouched', dataSet: [] },
      },
      StatsLeadConverted: {
        loading: false,
        view: ChartConfigViews.KPI,
        stepSize: 25,
        min: 0,
        max: 100,
        format: ChartConfigFormats.PERCENT,
        field: 'countLeadsClosedWithSale',
        generalStatsLabel: 'leadConverted',
        target: { label: 'leadsClosedWithSale', dataSet: [] },
      },
    },

    //--------------------------------------------------------------------------------------//
    //                                     Unsatisfied                                      //
    //--------------------------------------------------------------------------------------//

    [ChartConfigPages.COCKPIT_UNSATISFIED_GARAGES]: {
      StatsUnsatisfiedUnprocessed: {
        loading: false,
        view: ChartConfigViews.KPI,
        stepSize: 25,
        min: 0,
        max: 100,
        format: ChartConfigFormats.PERCENT_ROUND,
        field: 'countUnsatisfiedUntouched',
        generalStatsLabel: 'unsatisfiedUntreated',
        target: { label: 'unsatisfiedUntouched', dataSet: [] },
      },
      StatsUnsatisfiedProcessed: {
        loading: false,
        view: ChartConfigViews.KPI,
        stepSize: 25,
        min: 0,
        max: 100,
        format: ChartConfigFormats.PERCENT_ROUND,
        field: 'countUnsatisfiedTouched',
        generalStatsLabel: 'unsatisfiedPendingOrProcessed',
        target: { label: 'unsatisfiedTouched', dataSet: [] },
      },
      StatsUnsatisfiedSaved: {
        loading: false,
        view: ChartConfigViews.KPI,
        stepSize: 25,
        min: 0,
        max: 100,
        format: ChartConfigFormats.PERCENT_ROUND,
        field: 'countUnsatisfiedClosedWithResolution',
        generalStatsLabel: 'unsatisfiedSaved',
        target: { label: 'unsatisfiedClosedWithResolution', dataSet: [] },
      },
    },
    [ChartConfigPages.COCKPIT_UNSATISFIED_TEAM]: {
      StatsUnsatisfiedUnprocessed: {
        loading: false,
        view: ChartConfigViews.KPI,
        stepSize: 25,
        min: 0,
        max: 100,
        format: ChartConfigFormats.PERCENT_ROUND,
        field: 'countUnsatisfiedUntouched',
        generalStatsLabel: 'unsatisfiedUntreated',
        target: { label: 'unsatisfiedUntouched', dataSet: [] },
      },
      StatsUnsatisfiedProcessed: {
        loading: false,
        view: ChartConfigViews.KPI,
        stepSize: 25,
        min: 0,
        max: 100,
        format: ChartConfigFormats.PERCENT_ROUND,
        field: 'countUnsatisfiedTouched',
        generalStatsLabel: 'unsatisfiedPendingOrProcessed',
        target: { label: 'unsatisfiedTouched', dataSet: [] },
      },
      StatsUnsatisfiedSaved: {
        loading: false,
        view: ChartConfigViews.KPI,
        stepSize: 25,
        min: 0,
        max: 100,
        format: ChartConfigFormats.PERCENT_ROUND,
        field: 'countUnsatisfiedClosedWithResolution',
        generalStatsLabel: 'unsatisfiedSaved',
        target: { label: 'unsatisfiedClosedWithResolution', dataSet: [] },
      },
    },

    //--------------------------------------------------------------------------------------//
    //                                     Satisfaction                                     //
    //--------------------------------------------------------------------------------------//

    [ChartConfigPages.COCKPIT_SATISFACTION_GARAGES]: {
      StatsNPS: {
        loading: false,
        view: ChartConfigViews.KPI,
        stepSize: 25,
        max: 100,
        suggestedMin: 0,
        suggestedMax: 100,
        format: ChartConfigFormats.ROUND,
        field: 'satisfactionNPS',
        generalStatsLabel: 'nps',
        target: { label: 'NPS', dataSet: [] },
      },
      StatsPromotors: {
        loading: false,
        view: ChartConfigViews.KPI,
        stepSize: 25,
        min: 0,
        max: 100,
        format: ChartConfigFormats.PERCENT_ROUND,
        field: 'satisfactionCountPromoters',
        generalStatsLabel: 'promotors',
        target: { label: 'promotors', dataSet: [] },
      },
      StatsDetractors: {
        loading: false,
        view: ChartConfigViews.KPI,
        stepSize: 5,
        suggestedMax: 20,
        min: 0,
        format: ChartConfigFormats.PERCENT_ROUND,
        field: 'satisfactionCountDetractors',
        generalStatsLabel: 'detractors',
        target: { label: 'detractors', dataSet: [] },
      },
    },
    [ChartConfigPages.COCKPIT_SATISFACTION_TEAM]: {
      StatsNPS: {
        loading: false,
        view: ChartConfigViews.KPI,
        stepSize: 25,
        max: 100,
        suggestedMin: 0,
        suggestedMax: 100,
        format: ChartConfigFormats.ROUND,
        field: 'satisfactionNPS',
        generalStatsLabel: 'nps',
        target: { label: 'NPS', dataSet: [] },
      },
      StatsPromotors: {
        loading: false,
        view: ChartConfigViews.KPI,
        stepSize: 25,
        min: 0,
        max: 100,
        format: ChartConfigFormats.PERCENT_ROUND,
        field: 'satisfactionCountPromoters',
        generalStatsLabel: 'promotors',
        target: { label: 'promotors', dataSet: [] },
      },
      StatsDetractors: {
        loading: false,
        view: ChartConfigViews.KPI,
        stepSize: 5,
        suggestedMax: 20,
        min: 0,
        format: ChartConfigFormats.PERCENT_ROUND,
        field: 'satisfactionCountDetractors',
        generalStatsLabel: 'detractors',
        target: { label: 'detractors', dataSet: [] },
      },
    },
    [ChartConfigPages.COCKPIT_SATISFACTION_REVIEWS]: {
      StatsNPS: {
        loading: false,
        view: ChartConfigViews.KPI,
        stepSize: 25,
        max: 100,
        suggestedMin: 0,
        suggestedMax: 100,
        format: ChartConfigFormats.ROUND,
        field: 'satisfactionNPS',
        generalStatsLabel: 'nps',
        target: { label: 'NPS', dataSet: [] },
      },
      StatsPromotors: {
        loading: false,
        view: ChartConfigViews.KPI,
        stepSize: 25,
        min: 0,
        max: 100,
        format: ChartConfigFormats.PERCENT_ROUND,
        field: 'satisfactionCountPromoters',
        generalStatsLabel: 'promotors',
        target: { label: 'promotors', dataSet: [] },
      },
      StatsDetractors: {
        loading: false,
        view: ChartConfigViews.KPI,
        stepSize: 5,
        suggestedMax: 20,
        min: 0,
        format: ChartConfigFormats.PERCENT_ROUND,
        field: 'satisfactionCountDetractors',
        generalStatsLabel: 'detractors',
        target: { label: 'detractors', dataSet: [] },
      },
    },

    //--------------------------------------------------------------------------------------//
    //                                       Contacts                                       //
    //--------------------------------------------------------------------------------------//

    [ChartConfigPages.COCKPIT_CONTACTS_GARAGES]: {
      StatsResponded: {
        loading: false,
        view: ChartConfigViews.KPI,
        stepSize: 25,
        min: 0,
        max: 100,
        format: ChartConfigFormats.PERCENT_ROUND,
        field: 'respondents',
        generalStatsLabel: 'respondents',
        target: { label: 'respondents', dataSet: [] },
      },
      StatsValidEmails: {
        loading: false,
        view: ChartConfigViews.KPI,
        stepSize: 25,
        min: 0,
        max: 100,
        format: ChartConfigFormats.PERCENT_ROUND,
        field: 'validEmails',
        generalStatsLabel: 'validEmails',
        target: { label: 'validEmails', dataSet: [] },
      },
      StatsNotContactable: {
        loading: false,
        view: ChartConfigViews.KPI,
        stepSize: 5,
        suggestedMax: 20,
        min: 0,
        format: ChartConfigFormats.PERCENT,
        field: 'unreachables',
        generalStatsLabel: 'unreachables',
        target: { label: 'unreachables', dataSet: [] },
      },
    },
    [ChartConfigPages.COCKPIT_CONTACTS_TEAM]: {
      StatsResponded: {
        loading: false,
        view: ChartConfigViews.KPI,
        stepSize: 25,
        min: 0,
        max: 100,
        format: ChartConfigFormats.PERCENT_ROUND,
        field: 'respondents',
        generalStatsLabel: 'respondents',
        target: { label: 'respondents', dataSet: [] },
      },
      StatsValidEmails: {
        loading: false,
        view: ChartConfigViews.KPI,
        stepSize: 25,
        min: 0,
        max: 100,
        format: ChartConfigFormats.PERCENT_ROUND,
        field: 'validEmails',
        generalStatsLabel: 'validEmails',
        target: { label: 'validEmails', dataSet: [] },
      },
      StatsNotContactable: {
        loading: false,
        view: ChartConfigViews.KPI,
        stepSize: 5,
        suggestedMax: 20,
        min: 0,
        format: ChartConfigFormats.PERCENT,
        field: 'unreachables',
        generalStatsLabel: 'unreachables',
        target: { label: 'unreachables', dataSet: [] },
      },
    },
    [ChartConfigPages.COCKPIT_CONTACTS_REVIEWS]: {
      StatsResponded: {
        loading: false,
        view: ChartConfigViews.KPI,
        stepSize: 25,
        min: 0,
        max: 100,
        format: ChartConfigFormats.PERCENT_ROUND,
        field: 'respondents',
        generalStatsLabel: 'respondents',
        target: { label: 'respondents', dataSet: [] },
      },
      StatsValidEmails: {
        loading: false,
        view: ChartConfigViews.KPI,
        stepSize: 25,
        min: 0,
        max: 100,
        format: ChartConfigFormats.PERCENT_ROUND,
        field: 'validEmails',
        generalStatsLabel: 'validEmails',
        target: { label: 'validEmails', dataSet: [] },
      },
      StatsNotContactable: {
        loading: false,
        view: ChartConfigViews.KPI,
        stepSize: 5,
        suggestedMax: 20,
        min: 0,
        format: ChartConfigFormats.PERCENT,
        field: 'unreachables',
        generalStatsLabel: 'unreachables',
        target: { label: 'unreachables', dataSet: [] },
      },
    },

    //--------------------------------------------------------------------------------------//
    //                                     Ereputation                                      //
    //--------------------------------------------------------------------------------------//

    [ChartConfigPages.COCKPIT_E_REPUTATION_GARAGES]: {
      EreputationTileGarageScore: {
        loading: false,
        view: ChartConfigViews.KPI,
        stepSize: 2,
        min: 0,
        max: 10,
        field: 'erepRatingGaragescore',
        format: ChartConfigFormats.GRADE_10,
        target: { label: 'grade', dataSet: [] },
      },
      EreputationTileGoogle: {
        loading: false,
        view: ChartConfigViews.KPI,
        stepSize: 1,
        min: 0,
        max: 5,
        field: 'erepRatingGoogle',
        format: ChartConfigFormats.GRADE_5,
        target: { label: 'grade', dataSet: [] },
      },
      EreputationTileFacebook: {
        loading: false,
        view: ChartConfigViews.KPI,
        stepSize: 25,
        min: 0,
        max: 100,
        field: 'erepRatingFacebook',
        format: ChartConfigFormats.PERCENT,
        target: { label: 'recommend', dataSet: [] },
      },
      EreputationTilePagesJaunes: {
        loading: false,
        view: ChartConfigViews.KPI,
        stepSize: 1,
        min: 0,
        max: 5,
        field: 'erepRatingPagesJaunes',
        format: ChartConfigFormats.GRADE_5,
        target: { label: 'grade', dataSet: [] },
      },
    },
    [ChartConfigPages.COCKPIT_E_REPUTATION_REVIEWS]: {
      EreputationTileGarageScore: {
        loading: false,
        view: ChartConfigViews.KPI,
        stepSize: 2,
        min: 0,
        max: 10,
        field: 'erepRatingGaragescore',
        format: ChartConfigFormats.GRADE_10,
        target: { label: 'grade', dataSet: [] },
      },
      EreputationTileGoogle: {
        loading: false,
        view: ChartConfigViews.KPI,
        stepSize: 1,
        min: 0,
        max: 5,
        field: 'erepRatingGoogle',
        format: ChartConfigFormats.GRADE_5,
        target: { label: 'grade', dataSet: [] },
      },
      EreputationTileFacebook: {
        loading: false,
        view: ChartConfigViews.KPI,
        stepSize: 25,
        min: 0,
        max: 100,
        format: ChartConfigFormats.PERCENT,
        field: 'erepRatingFacebook',
        target: { label: 'recommend', dataSet: [] },
      },
      EreputationTilePagesJaunes: {
        loading: false,
        view: ChartConfigViews.KPI,
        stepSize: 1,
        min: 0,
        max: 5,
        field: 'erepRatingPagesJaunes',
        format: ChartConfigFormats.GRADE_5,
        target: { label: 'grade', dataSet: [] },
      },
    },

    //--------------------------------------------------------------------------------------//
    //                                      Automation                                      //
    //--------------------------------------------------------------------------------------//

    [ChartConfigPages.COCKPIT_AUTOMATION_GARAGES]: {
      StatsAutomationSent: {
        loading: false,
        view: ChartConfigViews.KPI,
        min: 0,
        field: 'countSent',
        target: { label: 'countSent', dataSet: [] },
      },
      StatsAutomationOpened: {
        loading: false,
        view: ChartConfigViews.KPI,
        min: 0,
        field: 'countOpened',
        target: { label: 'countOpened', dataSet: [] },
      },
      StatsAutomationConverted: {
        loading: false,
        view: ChartConfigViews.KPI,
        min: 0,
        field: 'countConverted',
        target: { label: 'countConverted', dataSet: [] },
      },
      StatsAutomationLead: {
        loading: false,
        view: ChartConfigViews.KPI,
        min: 0,
        field: 'countLeadSales',
        target: { label: 'countLeadSales', dataSet: [] },
      },
    },
    [ChartConfigPages.COCKPIT_AUTOMATION_CAMPAIGNS]: {
      StatsAutomationSent: {
        loading: false,
        view: ChartConfigViews.KPI,
        min: 0,
        field: 'countSent',
        target: { label: 'countSent', dataSet: [] },
      },
      StatsAutomationOpened: {
        loading: false,
        view: ChartConfigViews.KPI,
        min: 0,
        field: 'countOpened',
        target: { label: 'countOpened', dataSet: [] },
      },
      StatsAutomationConverted: {
        loading: false,
        view: ChartConfigViews.KPI,
        min: 0,
        field: 'countConverted',
        target: { label: 'countConverted', dataSet: [] },
      },
      StatsAutomationLead: {
        loading: false,
        view: ChartConfigViews.KPI,
        min: 0,
        field: 'countLeadSales',
        target: { label: 'countLeadSales', dataSet: [] },
      },
    },
  },
};

/* we call the config validator to log potential errors */
ChartConfigValidator.isValid(CHART_CONFIGURATION);

export default CHART_CONFIGURATION;
