const { ObjectId } = require('mongodb');
const ISODate = (date) => new Date(date);

module.exports = {
  _id: ObjectId('617ab480efbd732db48b7330'),
  garageId: '577a30d774616c1a0056c263',
  type: 'Maintenance',
  garageType: 'Dealership',
  shouldSurfaceInStatistics: true,
  service: {
    isQuote: null,
    providedAt: ISODate('2021-10-10T22:00:00.000Z'),
    frontDeskUserName: 'UNDEFINED',
    middleMans: ['paymentFacilities'],
    categories: ['Maintenance3'],
  },
  customer: {
    isValidated: true,
    contact: {
      email: {
        value: 'bb@test.com',
        original: 'bb@test.com',
        isSyntaxOK: true,
        isEmpty: false,
        isValidated: true,
      },
      mobilePhone: {
        value: '+33 6 12 34 56 78',
        original: '06 12 34 56 78',
        isSyntaxOK: true,
        isEmpty: false,
        isValidated: true,
      },
    },
    gender: {
      value: 'M',
      original: 'M',
      isSyntaxOK: true,
      isEmpty: false,
    },
    title: {
      value: 'Monsieur',
      original: 'Monsieur',
      isSyntaxOK: true,
      isEmpty: false,
      isValidated: true,
    },
    firstName: {
      value: 'Philippe',
      original: 'Philippe',
      isSyntaxOK: true,
      isEmpty: false,
    },
    lastName: {
      value: 'Robert',
      original: 'Robert',
      isSyntaxOK: true,
      isEmpty: false,
    },
    fullName: {
      value: 'Philippe Robert',
      original: 'Philippe Robert',
      isSyntaxOK: true,
      isEmpty: false,
      isValidated: true,
    },
    street: {
      value: '44 Rue Cauchy',
      original: '44 Rue Cauchy',
      isSyntaxOK: true,
      isEmpty: false,
      isValidated: true,
    },
    postalCode: {
      value: '94110',
      original: '94110',
      isSyntaxOK: true,
      isEmpty: false,
      isValidated: true,
    },
    city: {
      value: 'Arcueil',
      original: 'Arcueil',
      isSyntaxOK: true,
      isEmpty: false,
      isValidated: true,
    },
    countryCode: {
      value: 'FR',
      original: 'FR',
      isSyntaxOK: true,
      isEmpty: false,
    },
    rgpd: {
      optOutMailing: {
        isEmpty: true,
      },
      optOutSMS: {
        isEmpty: true,
      },
    },
  },
  vehicle: {
    isRevised: false,
    isValidated: false,
    make: {
      isEmpty: true,
    },
    model: {
      value: 'Clio',
      original: 'Clio',
      isSyntaxOK: true,
      isEmpty: false,
    },
    mileage: {
      isEmpty: true,
    },
    plate: {
      isEmpty: true,
    },
    vin: {
      isEmpty: true,
    },
    countryCode: {
      isEmpty: true,
    },
    registrationDate: {
      isEmpty: true,
    },
  },
  campaign: {
    campaignId: ObjectId('61640cb15605ac00045756be'),
    status: 'Running',
    importedAt: ISODate('2021-10-11T10:06:41.731Z'),
    contactStatus: {
      hasBeenContactedByPhone: false,
      hasBeenContactedByEmail: true,
      hasOriginalBeenContactedByPhone: false,
      hasOriginalBeenContactedByEmail: false,
      status: 'Received',
      phoneStatus: 'Empty',
      emailStatus: 'Valid',
      previouslyContactedByPhone: false,
      previouslyContactedByEmail: false,
      previouslyDroppedEmail: false,
      previouslyDroppedPhone: false,
      previouslyUnsubscribedByEmail: false,
      previouslyUnsubscribedByPhone: false,
      previouslyComplainedByEmail: false,
    },
    contactScenario: {
      deltaContact: 0,
      firstContactedAt: ISODate('2021-10-11T10:06:42.353Z'),
      nextCampaignReContactDay: 18946,
      nextCampaignContact: null,
      nextCampaignContactDay: null,
      lastCampaignContactSent: 'maintenance_email_thanks_2_make',
      lastCampaignContactSentAt: ISODate('2021-10-11T10:27:50.472Z'),
      nextCheckSurveyUpdatesDecaminute: null,
      firstContactByEmailDay: 18911,
      firstContactByPhoneDay: 18911,
      nextCampaignContactEvent: 'CONTACT_SENT',
      nextCampaignContactAt: ISODate('1970-01-01T00:00:00.000Z'),
    },
  },
  source: {
    sourceId: ObjectId('61640cb15605ac00045756b8'),
    importedAt: ISODate('2021-10-11T10:06:41.516Z'),
    raw: {
      index: 0,
      cells: {
        dateinter: '11/10/2021',
        genre: 'Mr',
        fullName: 'Philippe ROBERT',
        firstName: 'Philippe',
        lastName: 'ROBERT',
        email: 'bb@test.com',
        ville: 'Arcueil',
        rue: '44 rue Cauchy',
        cp: '94110',
        marque: 'Renault',
        modele: 'Clio',
        mobilePhone: '',
      },
    },
    type: 'DataFile',
  },
  createdAt: ISODate('2021-10-11T10:06:41.550Z'),
  updatedAt: ISODate('2021-10-11T10:29:12.376Z'),
  survey: {
    acceptNewResponses: false,
    lastRespondedAt: ISODate('2021-10-11T10:27:28.653Z'),
    firstRespondedAt: ISODate('2021-10-11T10:26:33.382Z'),
    foreignResponses: [
      {
        source: 'Internal survey',
        date: ISODate('2021-10-11T10:26:33.376Z'),
        payload: {
          rating: '9',
          isComplete: false,
          pageNumber: 0,
          pageCount: 5,
          timestamp: 1633947990812.0,
        },
      },
      {
        source: 'Internal survey',
        date: ISODate('2021-10-11T10:27:03.391Z'),
        payload: {
          rating: '0',
          acceptTermOfUse: true,
          dataType: 'Maintenance',
          leadType: 'InContactWithVendor',
          unsatisfiedCriteria: ['Maintenance1'],
          comment: 'test bb des lancement de jobs migrés en workers',
          isComplete: false,
          pageNumber: 1,
          pageCount: 5,
          timestamp: 1633948021278.0,
        },
      },
      {
        source: 'Internal survey',
        date: ISODate('2021-10-11T10:27:13.675Z'),
        payload: {
          rating: '0',
          acceptTermOfUse: true,
          dataType: 'Maintenance',
          leadType: 'InContactWithVendor',
          unsatisfiedCriteria: ['Maintenance1'],
          comment: 'test bb des lancement de jobs migrés en workers',
          leadTime: 'LongTerm',
          leadSaleType: 'Unknown',
          leadKnowVehicle: 'no',
          leadBodyType: ['Unknown'],
          leadEnergyType: ['hybrid'],
          leadTradeIn: 'YesOther',
          leadFunding: 'unknown',
          isComplete: false,
          pageNumber: 2,
          pageCount: 5,
          timestamp: 1633948032781.0,
        },
      },
      {
        source: 'Internal survey',
        date: ISODate('2021-10-11T10:27:18.646Z'),
        payload: {
          rating: '0',
          acceptTermOfUse: true,
          dataType: 'Maintenance',
          leadType: 'InContactWithVendor',
          unsatisfiedCriteria: ['Maintenance1'],
          comment: 'test bb des lancement de jobs migrés en workers',
          leadTime: 'LongTerm',
          leadSaleType: 'Unknown',
          leadKnowVehicle: 'no',
          leadBodyType: ['Unknown'],
          leadEnergyType: ['hybrid'],
          leadTradeIn: 'YesOther',
          leadFunding: 'unknown',
          unsatisfiedCriteria1: ['Maintenance3'],
          isComplete: false,
          pageNumber: 3,
          pageCount: 5,
          timestamp: 1633948035117.0,
        },
      },
      {
        source: 'Internal survey',
        date: ISODate('2021-10-11T10:27:23.645Z'),
        payload: {
          rating: '0',
          title: 'Monsieur',
          fullName: 'Philippe Robert',
          email: 'bb@test.com',
          streetAddress: '44 Rue Cauchy',
          postalCode: '94110',
          city: 'Arcueil',
          acceptTermOfUse: true,
          dataType: 'Maintenance',
          leadType: 'InContactWithVendor',
          unsatisfiedCriteria: ['Maintenance1'],
          comment: 'test bb des lancement de jobs migrés en workers',
          leadTime: 'LongTerm',
          leadSaleType: 'Unknown',
          leadKnowVehicle: 'no',
          leadBodyType: ['Unknown'],
          leadEnergyType: ['hybrid'],
          leadTradeIn: 'YesOther',
          leadFunding: 'unknown',
          unsatisfiedCriteria1: ['Maintenance3'],
          serviceMiddleMans: ['paymentFacilities'],
          serviceCategories: ['Maintenance3'],
          isComplete: false,
          pageNumber: 4,
          pageCount: 5,
          timestamp: 1633948039722.0,
        },
      },
      {
        source: 'Internal survey',
        date: ISODate('2021-10-11T10:27:28.647Z'),
        payload: {
          rating: '0',
          title: 'Monsieur',
          fullName: 'Philippe Robert',
          email: 'bb@test.com',
          streetAddress: '44 Rue Cauchy',
          postalCode: '94110',
          city: 'Arcueil',
          acceptTermOfUse: true,
          dataType: 'Maintenance',
          leadType: 'InContactWithVendor',
          comment: 'test bb des lancement de jobs migrés en workers',
          leadTime: 'LongTerm',
          leadSaleType: 'Unknown',
          leadKnowVehicle: 'no',
          leadBodyType: ['Unknown'],
          leadEnergyType: ['hybrid'],
          leadTradeIn: 'YesOther',
          leadFunding: 'unknown',
          serviceMiddleMans: ['paymentFacilities'],
          serviceCategories: ['Maintenance3'],
          shareWithPartners: 'Non',
          isComplete: true,
          pageNumber: 3,
          pageCount: 5,
          timestamp: 1633948043378.0,
        },
      },
    ],
    progress: {
      isComplete: true,
      pageCount: 5,
      pageNumber: 4,
    },
    urls: {
      base: 'https://beta-survey-pr-4810.herokuapp.com/s/786cd8a45b988ba57d786231b',
      baseShort: 'https://beta-app-pr-4810.herokuapp.com/cfdAompv1',
      mobileLanding: 'https://beta-survey-pr-4810.herokuapp.com/m/786cd8a45b988ba57d786231b',
      unsatisfiedLanding: 'https://beta-survey-pr-4810.herokuapp.com/u/786cd8a45b988ba57d786231b',
    },
    lastRespondentIP: '90.92.37.188',
    lastRespondentFingerPrint: 'f3a595de26397fbf00b03c9e906ef993',
    type: 'Maintenance',
    sendAt: ISODate('2021-10-11T10:06:42.300Z'),
    isIntern: true,
  },
  alert: {
    checkAlertHour: 453875,
  },
  lead: {
    reportedAt: ISODate('2021-10-11T10:27:29.646Z'),
    potentialSale: true,
    saleType: 'Unknown',
    timing: 'LongTerm',
    knowVehicle: false,
    vehicle: null,
    brands: null,
    energyType: ['hybrid'],
    bodyType: ['Unknown'],
    tradeIn: 'YesOther',
    financing: 'unknown',
    isConverted: false,
    isConvertedToSale: false,
    isConvertedToTradeIn: false,
    type: 'InContactWithVendor',
  },
  review: {
    createdAt: ISODate('2021-10-11T10:26:33.410Z'),
    rating: {
      value: 0,
    },
    comment: {
      text: 'test bb des lancement de jobs migrés en workers',
      status: 'Approved',
      updatedAt: ISODate('2021-10-11T10:27:03.434Z'),
      approvedAt: ISODate('2021-10-11T10:27:03.480Z'),
      rejectedReason: null,
    },
    shareWithPartners: false,
  },
  unsatisfied: {
    criteria: [
      {
        label: 'Maintenance1',
        values: ['Maintenance3'],
      },
    ],
  },
  leadTicket: {
    createdAt: ISODate('2021-10-11T10:27:50.552Z'),
    touched: false,
    reactive: false,
    status: 'WaitingForContact',
    actions: [
      {
        name: 'leadStarted',
        createdAt: ISODate('2021-10-11T10:27:50.743Z'),
        assignerUserId: null,
        ticketManagerId: ObjectId('5e7cd6cb4dc30a001605654a'),
        comment: '',
        isManual: false,
      },
    ],
    budget: NaN,
    manager: '5e7cd6cb4dc30a001605654a',
    comment: '',
    referenceDate: ISODate('2021-10-11T10:27:50.552Z'),
    temperature: 'Unknown',
    timing: 'LongTerm',
    saleType: 'Unknown',
    energyType: ['hybrid'],
    cylinder: [],
    bodyType: ['Unknown'],
    knowVehicle: false,
    financing: 'unknown',
    tradeIn: 'YesOther',
    customer: {
      contact: {
        mobilePhone: null,
        email: 'bb@test.com',
      },
      fullName: 'Philippe Robert',
    },
    leadVehicle: null,
    vehicle: {
      plate: null,
      makeModel: 'Clio',
    },
    type: 'Maintenance',
    brandModel: null,
    followUpDelayDays: 10,
  },
  unsatisfiedTicket: {
    createdAt: ISODate('2021-10-11T10:27:51.541Z'),
    touched: false,
    reactive: false,
    status: 'WaitingForContact',
    actions: [
      {
        name: 'unsatisfiedStarted',
        createdAt: ISODate('2021-10-11T10:27:51.541Z'),
        assignerUserId: null,
        ticketManagerId: ObjectId('5ea9e6477f2336001679f949'),
        comment: null,
        isManual: false,
      },
    ],
    manager: '5ea9e6477f2336001679f949',
    comment: '',
    referenceDate: ISODate('2021-10-11T10:27:51.541Z'),
    customer: {
      contact: {
        mobilePhone: null,
        email: 'bb@test.com',
      },
      fullName: 'Philippe Robert',
    },
    vehicle: {
      model: 'Clio',
      makeModel: ' 0',
    },
    frontDeskUserName: 'UNDEFINED',
    type: 'Maintenance',
    delayStatus: 'New',
    followUpDelayDays: 5,
  },
  surveyFollowupUnsatisfied: {
    acceptNewResponses: true,
    urls: {
      base:
        'https://beta-survey-pr-4810.herokuapp.com/s/786cd8a45b988ba57d786231b-c3VydmV5Rm9sbG93dXBVbnNhdGlzZmllZA==',
      baseShort: 'https://beta-app-pr-4810.herokuapp.com/w3fAompv1',
    },
    sendAt: ISODate('2021-10-11T10:28:26.881Z'),
  },
  surveyFollowupLead: {
    acceptNewResponses: true,
    urls: {
      base: 'https://beta-survey-pr-4810.herokuapp.com/s/786cd8a45b988ba57d786231b-c3VydmV5Rm9sbG93dXBMZWFk',
      baseShort: 'https://beta-app-pr-4810.herokuapp.com/mAnAompv1',
    },
    sendAt: ISODate('2021-10-11T10:29:12.354Z'),
  },
};
