import { makeApolloQueries } from '~/util/graphql';
import KpiTypes from '~/utils/models/kpi.type';

const fetchSingleKpiByPeriod = async (args) => {
  const request = {
    name: 'kpiByPeriodGetSingle',
    args,
    fields:
      ` totalShouldSurfaceInCampaignStats
        countEmails
        countSurveys
        countReceivedSurveys
        countSurveysResponded
        countSurveySatisfied
        countSurveyUnsatisfied
        countSurveyLead
        countSurveyLeadVo
        countSurveyLeadVn
        countValidEmails
        countBlockedByEmail
        countBlockedLastMonthEmail
        countUnsubscribedByEmail
        countWrongEmails
        countNotPresentEmails
        countValidPhones
        countBlockedByPhone
        countWrongPhones
        countNotPresentPhones
        countBlocked
        countNotContactable
        countSurveyRespondedAPV
        countSurveyRespondedVN
        countSurveyRespondedVO
        countScheduledContacts
        `,
  };
  const resp = await makeApolloQueries([request]);
  return resp?.data?.kpiByPeriodGetSingle ?? {};
};

const fetchKpi = async (args, usersKpi = false, garagesKpi = false) => {
  const {
    periodId,
    garageId,
    cockpitType,
    userId,
    followed,
  } = args;

  const request = {
    name: 'kpiByPeriodGetKpi',
    args: {
      periodId,
      garageId,
      cockpitType,
      userId,
      ...(followed ? { kpiType: KpiTypes.AGENT_GARAGE_KPI } : {}),
    },
    fields:
      `${garagesKpi ? `garagesKpi {
                countLeads
                countLeadsUnassigned
                countLeadsAssigned
                countLeadsUntouched
                countLeadsUntouchedOpen
                countLeadsTouched
                countLeadsTouchedOpen
                countLeadsTouchedClosed
                countLeadsReactive
                countLeadsWaitingForContact
                countLeadsContactPlanned
                countLeadsWaitingForMeeting
                countLeadsMeetingPlanned
                countLeadsWaitingForProposition
                countLeadsPropositionPlanned
                countLeadsWaitingForClosing
                countLeadsClosedWithoutSale
                countLeadsClosedWithSale
                countLeadsClosedWithSaleWasInterested
                countLeadsClosedWithSaleWasInContactWithVendor
                countLeadsClosedWithSaleWasAlreadyPlannedOtherBusiness
                countLeadsApv
                countLeadsUnassignedApv
                countLeadsAssignedApv
                countLeadsUntouchedApv
                countLeadsUntouchedOpenApv
                countLeadsTouchedApv
                countLeadsTouchedOpenApv
                countLeadsTouchedClosedApv
                countLeadsReactiveApv
                countLeadsWaitingForContactApv
                countLeadsContactPlannedApv
                countLeadsWaitingForMeetingApv
                countLeadsMeetingPlannedApv
                countLeadsWaitingForPropositionApv
                countLeadsPropositionPlannedApv
                countLeadsWaitingForClosingApv
                countLeadsClosedWithoutSaleApv
                countLeadsClosedWithSaleApv
                countLeadsClosedWithSaleWasInterestedApv
                countLeadsClosedWithSaleWasInContactWithVendorApv
                countLeadsClosedWithSaleWasAlreadyPlannedOtherBusinessApv
                countLeadsVn
                countLeadsUnassignedVn
                countLeadsAssignedVn
                countLeadsUntouchedVn
                countLeadsUntouchedOpenVn
                countLeadsTouchedVn
                countLeadsTouchedOpenVn
                countLeadsTouchedClosedVn
                countLeadsReactiveVn
                countLeadsWaitingForContactVn
                countLeadsContactPlannedVn
                countLeadsWaitingForMeetingVn
                countLeadsMeetingPlannedVn
                countLeadsWaitingForPropositionVn
                countLeadsPropositionPlannedVn
                countLeadsWaitingForClosingVn
                countLeadsClosedWithoutSaleVn
                countLeadsClosedWithSaleVn
                countLeadsClosedWithSaleWasInterestedVn
                countLeadsClosedWithSaleWasInContactWithVendorVn
                countLeadsClosedWithSaleWasAlreadyPlannedOtherBusinessVn
                countLeadsVo
                countLeadsUnassignedVo
                countLeadsAssignedVo
                countLeadsUntouchedVo
                countLeadsUntouchedOpenVo
                countLeadsTouchedVo
                countLeadsTouchedOpenVo
                countLeadsTouchedClosedVo
                countLeadsReactiveVo
                countLeadsWaitingForContactVo
                countLeadsContactPlannedVo
                countLeadsWaitingForMeetingVo
                countLeadsMeetingPlannedVo
                countLeadsWaitingForPropositionVo
                countLeadsPropositionPlannedVo
                countLeadsWaitingForClosingVo
                countLeadsClosedWithoutSaleVo
                countLeadsClosedWithSaleVo
                countLeadsClosedWithSaleWasInterestedVo
                countLeadsClosedWithSaleWasInContactWithVendorVo
                countLeadsClosedWithSaleWasAlreadyPlannedOtherBusinessVo
                countLeadsUnknown
                countLeadsUnassignedUnknown
                countLeadsAssignedUnknown
                countLeadsUntouchedUnknown
                countLeadsUntouchedOpenUnknown
                countLeadsTouchedUnknown
                countLeadsTouchedOpenUnknown
                countLeadsTouchedClosedUnknown
                countLeadsReactiveUnknown
                countLeadsWaitingForContactUnknown
                countLeadsContactPlannedUnknown
                countLeadsWaitingForMeetingUnknown
                countLeadsMeetingPlannedUnknown
                countLeadsWaitingForPropositionUnknown
                countLeadsPropositionPlannedUnknown
                countLeadsWaitingForClosingUnknown
                countLeadsClosedWithoutSaleUnknown
                countLeadsClosedWithSaleUnknown
                countLeadsClosedWithSaleWasInterestedUnknown
                countLeadsClosedWithSaleWasInContactWithVendorUnknown
                countLeadsClosedWithSaleWasAlreadyPlannedOtherBusinessUnknown
                countUnsatisfied
                countUnsatisfiedAssigned
                countUnsatisfiedOpenUnassigned
                countUnsatisfiedWaitingForContact
                countUnsatisfiedContactPlanned
                countUnsatisfiedWaitingForVisit
                countUnsatisfiedVisitPlanned
                countUnsatisfiedWaitingForClosing
                countUnsatisfiedClosedWithoutResolution
                countUnsatisfiedClosedWithResolution
                countUnsatisfiedUntouched
                countUnsatisfiedUntouchedOpen
                countUnsatisfiedTouched
                countUnsatisfiedTouchedOpen
                countUnsatisfiedTouchedClosed
                countUnsatisfiedReactive
                countUnsatisfiedApv
                countUnsatisfiedAssignedApv
                countUnsatisfiedOpenUnassignedApv
                countUnsatisfiedWaitingForContactApv
                countUnsatisfiedContactPlannedApv
                countUnsatisfiedWaitingForVisitApv
                countUnsatisfiedVisitPlannedApv
                countUnsatisfiedWaitingForClosingApv
                countUnsatisfiedClosedWithoutResolutionApv
                countUnsatisfiedClosedWithResolutionApv
                countUnsatisfiedUntouchedApv
                countUnsatisfiedUntouchedOpenApv
                countUnsatisfiedTouchedApv
                countUnsatisfiedTouchedOpenApv
                countUnsatisfiedTouchedClosedApv
                countUnsatisfiedReactiveApv
                countUnsatisfiedVo
                countUnsatisfiedAssignedVo
                countUnsatisfiedOpenUnassignedVo
                countUnsatisfiedWaitingForContactVo
                countUnsatisfiedContactPlannedVo
                countUnsatisfiedWaitingForVisitVo
                countUnsatisfiedVisitPlannedVo
                countUnsatisfiedWaitingForClosingVo
                countUnsatisfiedClosedWithoutResolutionVo
                countUnsatisfiedClosedWithResolutionVo
                countUnsatisfiedUntouchedVo
                countUnsatisfiedUntouchedOpenVo
                countUnsatisfiedTouchedVo
                countUnsatisfiedTouchedOpenVo
                countUnsatisfiedTouchedClosedVo
                countUnsatisfiedReactiveVo
                countUnsatisfiedVn
                countUnsatisfiedAssignedVn
                countUnsatisfiedOpenUnassignedVn
                countUnsatisfiedWaitingForContactVn
                countUnsatisfiedContactPlannedVn
                countUnsatisfiedWaitingForVisitVn
                countUnsatisfiedVisitPlannedVn
                countUnsatisfiedWaitingForClosingVn
                countUnsatisfiedClosedWithoutResolutionVn
                countUnsatisfiedClosedWithResolutionVn
                countUnsatisfiedUntouchedVn
                countUnsatisfiedUntouchedOpenVn
                countUnsatisfiedTouchedVn
                countUnsatisfiedTouchedOpenVn
                countUnsatisfiedTouchedClosedVn
                countUnsatisfiedReactiveVn
            }` : ''}
            ${usersKpi ? `
            usersKpi {
                countLeads
                countLeadsUnassigned
                countLeadsAssigned
                countLeadsUntouched
                countLeadsUntouchedOpen
                countLeadsTouched
                countLeadsTouchedOpen
                countLeadsTouchedClosed
                countLeadsReactive
                countLeadsWaitingForContact
                countLeadsContactPlanned
                countLeadsWaitingForMeeting
                countLeadsMeetingPlanned
                countLeadsWaitingForProposition
                countLeadsPropositionPlanned
                countLeadsWaitingForClosing
                countLeadsClosedWithoutSale
                countLeadsClosedWithSale
                countLeadsClosedWithSaleWasInterested
                countLeadsClosedWithSaleWasInContactWithVendor
                countLeadsClosedWithSaleWasAlreadyPlannedOtherBusiness
                countLeadsApv
                countLeadsUnassignedApv
                countLeadsAssignedApv
                countLeadsUntouchedApv
                countLeadsUntouchedOpenApv
                countLeadsTouchedApv
                countLeadsTouchedOpenApv
                countLeadsTouchedClosedApv
                countLeadsReactiveApv
                countLeadsWaitingForContactApv
                countLeadsContactPlannedApv
                countLeadsWaitingForMeetingApv
                countLeadsMeetingPlannedApv
                countLeadsWaitingForPropositionApv
                countLeadsPropositionPlannedApv
                countLeadsWaitingForClosingApv
                countLeadsClosedWithoutSaleApv
                countLeadsClosedWithSaleApv
                countLeadsClosedWithSaleWasInterestedApv
                countLeadsClosedWithSaleWasInContactWithVendorApv
                countLeadsClosedWithSaleWasAlreadyPlannedOtherBusinessApv
                countLeadsVn
                countLeadsUnassignedVn
                countLeadsAssignedVn
                countLeadsUntouchedVn
                countLeadsUntouchedOpenVn
                countLeadsTouchedVn
                countLeadsTouchedOpenVn
                countLeadsTouchedClosedVn
                countLeadsReactiveVn
                countLeadsWaitingForContactVn
                countLeadsContactPlannedVn
                countLeadsWaitingForMeetingVn
                countLeadsMeetingPlannedVn
                countLeadsWaitingForPropositionVn
                countLeadsPropositionPlannedVn
                countLeadsWaitingForClosingVn
                countLeadsClosedWithoutSaleVn
                countLeadsClosedWithSaleVn
                countLeadsClosedWithSaleWasInterestedVn
                countLeadsClosedWithSaleWasInContactWithVendorVn
                countLeadsClosedWithSaleWasAlreadyPlannedOtherBusinessVn
                countLeadsVo
                countLeadsUnassignedVo
                countLeadsAssignedVo
                countLeadsUntouchedVo
                countLeadsUntouchedOpenVo
                countLeadsTouchedVo
                countLeadsTouchedOpenVo
                countLeadsTouchedClosedVo
                countLeadsReactiveVo
                countLeadsWaitingForContactVo
                countLeadsContactPlannedVo
                countLeadsWaitingForMeetingVo
                countLeadsMeetingPlannedVo
                countLeadsWaitingForPropositionVo
                countLeadsPropositionPlannedVo
                countLeadsWaitingForClosingVo
                countLeadsClosedWithoutSaleVo
                countLeadsClosedWithSaleVo
                countLeadsClosedWithSaleWasInterestedVo
                countLeadsClosedWithSaleWasInContactWithVendorVo
                countLeadsClosedWithSaleWasAlreadyPlannedOtherBusinessVo
                countLeadsUnknown
                countLeadsUnassignedUnknown
                countLeadsAssignedUnknown
                countLeadsUntouchedUnknown
                countLeadsUntouchedOpenUnknown
                countLeadsTouchedUnknown
                countLeadsTouchedOpenUnknown
                countLeadsTouchedClosedUnknown
                countLeadsReactiveUnknown
                countLeadsWaitingForContactUnknown
                countLeadsContactPlannedUnknown
                countLeadsWaitingForMeetingUnknown
                countLeadsMeetingPlannedUnknown
                countLeadsWaitingForPropositionUnknown
                countLeadsPropositionPlannedUnknown
                countLeadsWaitingForClosingUnknown
                countLeadsClosedWithoutSaleUnknown
                countLeadsClosedWithSaleUnknown
                countLeadsClosedWithSaleWasInterestedUnknown
                countLeadsClosedWithSaleWasInContactWithVendorUnknown
                countLeadsClosedWithSaleWasAlreadyPlannedOtherBusinessUnknown
                countUnsatisfied
                countUnsatisfiedAssigned
                countUnsatisfiedOpenUnassigned
                countUnsatisfiedWaitingForContact
                countUnsatisfiedContactPlanned
                countUnsatisfiedWaitingForVisit
                countUnsatisfiedVisitPlanned
                countUnsatisfiedWaitingForClosing
                countUnsatisfiedClosedWithoutResolution
                countUnsatisfiedClosedWithResolution
                countUnsatisfiedUntouched
                countUnsatisfiedUntouchedOpen
                countUnsatisfiedTouched
                countUnsatisfiedTouchedOpen
                countUnsatisfiedTouchedClosed
                countUnsatisfiedReactive
                countUnsatisfiedApv
                countUnsatisfiedAssignedApv
                countUnsatisfiedOpenUnassignedApv
                countUnsatisfiedWaitingForContactApv
                countUnsatisfiedContactPlannedApv
                countUnsatisfiedWaitingForVisitApv
                countUnsatisfiedVisitPlannedApv
                countUnsatisfiedWaitingForClosingApv
                countUnsatisfiedClosedWithoutResolutionApv
                countUnsatisfiedClosedWithResolutionApv
                countUnsatisfiedUntouchedApv
                countUnsatisfiedUntouchedOpenApv
                countUnsatisfiedTouchedApv
                countUnsatisfiedTouchedOpenApv
                countUnsatisfiedTouchedClosedApv
                countUnsatisfiedReactiveApv
                countUnsatisfiedVo
                countUnsatisfiedAssignedVo
                countUnsatisfiedOpenUnassignedVo
                countUnsatisfiedWaitingForContactVo
                countUnsatisfiedContactPlannedVo
                countUnsatisfiedWaitingForVisitVo
                countUnsatisfiedVisitPlannedVo
                countUnsatisfiedWaitingForClosingVo
                countUnsatisfiedClosedWithoutResolutionVo
                countUnsatisfiedClosedWithResolutionVo
                countUnsatisfiedUntouchedVo
                countUnsatisfiedUntouchedOpenVo
                countUnsatisfiedTouchedVo
                countUnsatisfiedTouchedOpenVo
                countUnsatisfiedTouchedClosedVo
                countUnsatisfiedReactiveVo
                countUnsatisfiedVn
                countUnsatisfiedAssignedVn
                countUnsatisfiedOpenUnassignedVn
                countUnsatisfiedWaitingForContactVn
                countUnsatisfiedContactPlannedVn
                countUnsatisfiedWaitingForVisitVn
                countUnsatisfiedVisitPlannedVn
                countUnsatisfiedWaitingForClosingVn
                countUnsatisfiedClosedWithoutResolutionVn
                countUnsatisfiedClosedWithResolutionVn
                countUnsatisfiedUntouchedVn
                countUnsatisfiedUntouchedOpenVn
                countUnsatisfiedTouchedVn
                countUnsatisfiedTouchedOpenVn
                countUnsatisfiedTouchedClosedVn
                countUnsatisfiedReactiveVn
            }` : ''}`,
  };
  const resp = await makeApolloQueries([request]);
  return resp?.data?.kpiByPeriodGetKpi ?? {};
};

export { fetchSingleKpiByPeriod, fetchKpi };
