//en majuscule les colonnes 'parents' qui possèdent des attributs 'enfants'

const HEADERS = [
  'Garage Id',
  'External Id',
  'Type',
  'Groupe',
  'Statut branchement',
  'Siret',
  'Nom',
  'Adresse postale',
  'Code postal',
  'Ville',
  'Langue',
  'Miroir',
  'Etabl. de rattachement',
  'Date démarrage abonnement',
  'SETUP',
  'Date de paiement',
  'Prix',
  'MAINTENANCE',
  'Date',
  'Prix',
  'VÉHICULE NEUF',
  'Date',
  'Prix',
  "VÉHICULE D'OCCASION",
  'Date',
  'Prix',
  'CONTRÔLE TECHNIQUE',
  'Date',
  'Prix',
  "PROJET D'ACHAT",
  'Date',
  'Prix',
  'ANALYTICS',
  'Date',
  'Prix',
  'E-RÉPUTATION',
  'Date',
  'Prix',
  'AUTOMATION',
  'Date',
  'Inclus',
  'Prix',
  'Prix unitaire',
  'X-LEADS',
  'Date',
  'Inclus',
  'Prix',
  'Prix Unitaire',
  'Prix mobile par minutes',
  'COACHING',
  'Date',
  'Prix',
  'CONNECT',
  'Date',
  'Prix',
  'UTILISATEURS',
  'Inclus',
  'Prix unitaire',
  'CONTACTS',
  'Facturation par tranche de 100',
  'Prix unitaire',
  'Inclus',
  'Marques certificats',
  'Performance Manager',
  'Business Dev',
  'Tags',
];

module.exports = HEADERS;
