export enum HOUSING_FORM_NAMES {
  name = 'name',
  country = 'country',
  province = 'province',
  address = 'address',
  city = 'city',
  vatin = 'vatin',
  contract_type = 'contract_type',
  tourism_registration_number = 'tourism_registration_number',
  manager_name = 'manager_name',
  manager_phone = 'manager_phone',
  manager_birth_date = 'manager_birth_date',
  rooms_quantity = 'rooms_quantity',
  email_language = 'default_email_language',
  depositAmount = 'security_deposit_amount',
  security_deposit_status = 'security_deposit_status',
  booking_exempt_sources = 'booking_exempt_sources',
  tax_exempt_sources = 'tax_exempt_sources',
  deposit_exempt_sources = 'deposit_exempt_sources',
  is_biometric_match_for_all_enabled = 'is_biometric_match_for_all_enabled',
  number_of_spaces = 'number_of_spaces',
  booking_sources = 'booking_sources',
  verification_type = 'verification_type',
  is_self_online_check_in_enabled = 'is_self_online_check_in_enabled',
  commission_responsibility_for_tourist_tax = 'commission_responsibility_for_tourist_tax',
  external_housing = 'external_housing_id',
  available_rooms = 'available_rooms',
}
