var debug = require('debug')('garagescore:common:lib:garagescore:data-file:import-schema:ERIC:maurel'); // eslint-disable-line max-len,no-unused-vars
var vehicleMake = require('../vehicle-make');
/** shared arguments to create Maurel importer schemas*/
var shared = {
  columns: {
    dataRecordCompletedAt: [
      'dateinter',
      'Date de dernière visite',
      'date',
      'Date de facture',
      'Date MEC',
      'Date Facture',
      'Date Achat',
      'Date Facturation',
      'D. Dernier OR',
      'Commande Date livraison réelle',
      'DATE FACT ATE',
    ],
    gender: [
      'genre',
      'juridique',
      'Titre',
      'Civilité',
      'Client Propriétaire (titre)',
      'Client Civilité courte',
      'CIVILITE',
    ],
    fullName: ['fullName', 'nom', 'Nom', 'Nom Client'],
    lastName: ['lastName', 'nom', 'Nom', 'Client Propriétaire (nom 1)', 'Client Nom', 'NOM DU CLIENT', 'Nom individu'],
    firstName: ['firstName', 'prénom', 'Prénom', 'Client Propriétaire (prénom)', 'Client Prénom'],
    vehicleRegistrationPlate: ['Immatriculation', 'IMMAT'],
    mobilePhone: [
      'mobilePhone',
      'Tél. Portable',
      'portable',
      'Tel Portable',
      'courriel',
      'Tél. Mobile',
      'Tél Portable',
      'Client Portable',
      'PORTABLE',
      'Téléphone portable',
      'Tèl. portable',
    ],
    email: [
      'email',
      'e-mail',
      'mail',
      'Courriel',
      'Email',
      'Mail',
      'E-mail Particulier',
      'Adresse électronique',
      'Mail Domicile',
      'Client Email',
      'EMAIL',
      'courriel',
      'Email individu',
    ],
    streetAddress: ['Adresse 1', 'rue', 'Adresse'],
    postCode: ['Code Postal', 'cp', 'C. Postal'],
    city: ['ville', 'Ville', 'distributeur', 'VILLE'],
    vehicleMake: ['marque', 'Marque', 'Marque (véhicule)', 'Offre Marque', 'MARQUE'],
    vehicleVin: ['VIN', 'vehicleVin'],
    vehicleModel: ['modele', 'Série', 'Modéle véhicule', 'Modèle', 'Version', 'Offre Modèle', 'LIBELLE MODELE'],
    rowType: ['RtYpE', 'Service', 'Offre Type offre'],
  },
  foreigns: {
    providedFrontDeskUserName: [
      'Nom vendeur1',
      'Libellé réceptionnaire',
      'Nom Conseiller comm. principal',
      'vendeur',
      'interlocuteur',
      'Interlocuteur',
      'Nom Conseiller comm． principal',
      'Réceptionnaire',
      'Dernier Réceptionnaire',
      'NUMERO RECEPTIONNAIRE',
    ],
  },
  format: {
    vehicleMake: vehicleMake,
  },
};

module.exports = {
  shared: shared,
};
