version: 0.2
env:
  variables:
    DOCKER_REGISTRY: "358099927528.dkr.ecr.eu-central-1.amazonaws.com"
    DOCKER_REPO: "front/chekin-online"
phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region eu-central-1)
  build:
    commands:
      - echo Building
      - export DOCKER_TAG=git-${CODEBUILD_RESOLVED_SOURCE_VERSION}
      - export DOCKER_REPO=${DOCKER_REPO}${GIT_BRANCH}
      - docker build -t ${DOCKER_REGISTRY}/${DOCKER_REPO}:${DOCKER_TAG}  -f staging.Dockerfile .
      - docker tag ${DOCKER_REGISTRY}/${DOCKER_REPO}:${DOCKER_TAG} ${DOCKER_REGISTRY}/${DOCKER_REPO}:staging
      - docker push ${DOCKER_REGISTRY}/${DOCKER_REPO}:${DOCKER_TAG}
      - docker push ${DOCKER_REGISTRY}/${DOCKER_REPO}:staging
